### ISSUE TITLE
Suggestion: Change background color in the body

### ISSUE THREAD

**Issue by Mac-Jones-2** [Mac-Jones/git-github-crashcourse#1]
I think it looks better to change the background-color to orangered

```css
body {
	background-color: orangered;
}
```
