### ISSUE TITLE
Suggestion: Add aditional styles

### ISSUE THREAD

**Issue by Mac-Jones-2** [Mac-Jones/git-github-crashcourse#4]
```css 
.description {
	background-color: orange;
	width: fit-content;
	padding: 20px;
	border: 5px solid red;
	font-size: 19px;
	font-weight: 600;
	text-transform: uppercase;
	border-radius: 100px;
}
```
